### ISSUE TITLE
Issue while doing ./mc

### ISSUE THREAD

**Issue by GeorgN** [paulvha/rfid-rc522#1]
You've done a great job by building this program! It worked fine under Ubuntu Mate 15.10. For some reasons I migrated to 16.04 beta 2. During the installation process and doing ./mc  I've got this notification and a lot of warnings:
config.c:182:33: warning: format ‘%x’ expects argument of type ‘unsigned int *’, but argument 3 has type ‘uint8_t \* {aka unsigned char *}’

At the end of this all, rc522 didn't work as under Ubuntu Mate 15.10. What did I do wrong? Thank you very much in advance for your advice.

**Comment by paulvha** [comment]
I checked, indeed according to the specification sscanf %x is expecting int *, unlike printf() where the value is promoted to 'int' before passing,  I suspect that 16.04 beta 2 has a new compiler, that is more strict. let me try to adjust the code and test it

**Comment by paulvha** [comment]
New version (1.1) has been added. Should work, but can not check against Ubuntu. Let me know whether it worked.

**Comment by GeorgN** [comment]
I've tried your new version. Results are shown here:
main.c: In function ‘key_upd’:
main.c:62:16: warning: too many arguments for format [-Wformat-extra-args]
 #define YLWSTR "\e[1;93m%s\e[00m"
                ^
main.c:153:17: note: in expansion of macro ‘YLWSTR’
         printf (YLWSTR,"Do you want to provide s = sector or b = block number f
                 ^
main.c:250:25: warning: format ‘%x’ expects argument of type ‘unsigned int _’, but argument 2 has type ‘uint8_t \* {aka unsigned char *}’ [-Wformat=]
             tmp = scanf("%x", &new_key[i]);
                         ^
main.c:280:15: warning: format ‘%s’ expects argument of type ‘char *’, but argument 2 has type ‘char (_)[50]’ [-Wformat=]
         scanf("%s", &buf);
               ^
main.c:297:9: warning: implicit declaration of function ‘get_card_info’ [-Wimplicit-function-declaration]
     if (get_card_info() != TAG_OK)    return(1);
         ^
main.c:340:9: warning: implicit declaration of function ‘authorize’ [-Wimplicit-function-declaration]
     if (authorize(SN, t_addr,PICC_AUTHENT1A) != TAG_OK) return(1);
         ^
main.c:429:9: warning: implicit declaration of function ‘add_to_config’ [-Wimplicit-function-declaration]
     if (add_to_config(buf)){
         ^
main.c: In function ‘addr_action’:
main.c:723:12: warning: implicit declaration of function ‘perform_action’ [-Wimplicit-function-declaration]
     return(perform_action());
            ^
main.c: In function ‘change_con’:
main.c:60:16: warning: format ‘%s’ expects a matching ‘char *’ argument [-Wformat=]
 #define REDSTR "\e[1;31m%s\e[00m"
                ^
main.c:750:20: note: in expansion of macro ‘REDSTR’
             printf(REDSTR"Block can't be below 0.\n");
                    ^
main.c:60:16: warning: format ‘%s’ expects a matching ‘char *’ argument [-Wformat=]
 #define REDSTR "\e[1;31m%s\e[00m"
                ^
main.c:755:21: note: in expansion of macro ‘REDSTR’
             printf (REDSTR"Can not change access to trailer.\n");
                     ^
main.c:852:16: warning: too many arguments for format [-Wformat-extra-args]
         printf("YLWSTR","| 3.\tkeyB\tkeyB\tnever\t\tnever\t\t(read/write block)
                ^
main.c: In function ‘write_to_card’:
main.c:1201:29: warning: format ‘%x’ expects argument of type ‘unsigned int *’, but argument 2 has type ‘uint8_t \* {aka unsigned char *}’ [-Wformat=]
                 tmp = scanf("%x", &value[i]);
                             ^
main.c: At top level:
main.c:1253:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
 read_card_to_file()
 ^
Will this help you? Feel free to drop me a line, if you need some additional information.

**Comment by paulvha** [comment]
Thanks

I will have a look later today.

Verzonden vanuit Outlook Mobile

On Tue, Apr 19, 2016 at 5:40 AM -0700, "GeorgN" notifications@github.com wrote:

I've tried your new version. Results are shown here:
main.c: In function ‘key_upd’:
main.c:62:16: warning: too many arguments for format [-Wformat-extra-args]
 #define YLWSTR "\e[1;93m%s\e[00m"
                ^
main.c:153:17: note: in expansion of macro ‘YLWSTR’
         printf (YLWSTR,"Do you want to provide s = sector or b = block number f
                 ^
main.c:250:25: warning: format ‘%x’ expects argument of type ‘unsigned int _’, but argument 2 has type ‘uint8_t \* {aka unsigned char *}’ [-Wformat=]
             tmp = scanf("%x", &new_key[i]);
                         ^
main.c:280:15: warning: format ‘%s’ expects argument of type ‘char *’, but argument 2 has type ‘char (_)[50]’ [-Wformat=]
         scanf("%s", &buf);
               ^
main.c:297:9: warning: implicit declaration of function ‘get_card_info’ [-Wimplicit-function-declaration]
     if (get_card_info() != TAG_OK)    return(1);
         ^
main.c:340:9: warning: implicit declaration of function ‘authorize’ [-Wimplicit-function-declaration]
     if (authorize(SN, t_addr,PICC_AUTHENT1A) != TAG_OK) return(1);
         ^
main.c:429:9: warning: implicit declaration of function ‘add_to_config’ [-Wimplicit-function-declaration]
     if (add_to_config(buf)){
         ^
main.c: In function ‘addr_action’:
main.c:723:12: warning: implicit declaration of function ‘perform_action’ [-Wimplicit-function-declaration]
     return(perform_action());
            ^
main.c: In function ‘change_con’:
main.c:60:16: warning: format ‘%s’ expects a matching ‘char *’ argument [-Wformat=]
 #define REDSTR "\e[1;31m%s\e[00m"
                ^
main.c:750:20: note: in expansion of macro ‘REDSTR’
             printf(REDSTR"Block can't be below 0.\n");
                    ^
main.c:60:16: warning: format ‘%s’ expects a matching ‘char *’ argument [-Wformat=]
 #define REDSTR "\e[1;31m%s\e[00m"
                ^
main.c:755:21: note: in expansion of macro ‘REDSTR’
             printf (REDSTR"Can not change access to trailer.\n");
                     ^
main.c:852:16: warning: too many arguments for format [-Wformat-extra-args]
         printf("YLWSTR","| 3.\tkeyB\tkeyB\tnever\t\tnever\t\t(read/write block)
                ^
main.c: In function ‘write_to_card’:
main.c:1201:29: warning: format ‘%x’ expects argument of type ‘unsigned int *’, but argument 2 has type ‘uint8_t \* {aka unsigned char *}’ [-Wformat=]
                 tmp = scanf("%x", &value[i]);
                             ^
main.c: At top level:
main.c:1253:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
 read_card_to_file()
 ^
Will this help you? Feel free to drop me a line, if you need some additional information.

---

**Comment by paulvha** [comment]
That  compiler is very strict, BUT correct ! none of these errors show up under Debian ( Wheezy nor Jessie)
made the changes to the code (see in between) to be posted as 1.11.

Date: Tue, 19 Apr 2016 05:40:31 -0700

**Comment by paulvha** [comment]
new version is now posted. it compiled and worked without a problem on Debian (Jessie). 
please let me know your result(s)

**Comment by GeorgN** [comment]
The new result is:
main.c: In function ‘key_upd’:
main.c:283:15: warning: format ‘%s’ expects argument of type ‘char _’, but argument 2 has type ‘char (_)[50]’ [-Wformat=]
         scanf("%s", &buf);
               ^
It seems to look better, only one warning.

**Comment by paulvha** [comment]
thanks... try to remove the & before buf... removing it will also compile without errors on Debian...

**Comment by GeorgN** [comment]
thanks ... after the modification the compiler worked.

By testing the program rc522 I 've got following results:
1.  ./rc522 [options]:           (version 1.11)
      -d  enable debug mode
      -w  write to card block
      -r  read a card block
      -s  save content all card blocks in a file
      -p  perform action on card number (specified in configuration file)
      -c  change access rights for specific block
      -a  perform action based on content specific block
      -k  Change authentication key on a specific sector
That seems to be ok.
2. ./rc522 -s
and nothing happened ...

**Comment by paulvha** [comment]
Thanks George,

I just checked the code and connected the rc522. It is reading the card to file in my case as expected.

Have you copied RC522.conf to  /etc?

Have you set NEW_TAG_PATH in /etc/RC522.conf?

```
            If correct, this will keep “save_mem” enabled (as done with -s option) and  will allow to call read_card_to_file in line 1539 in main.c

            If the variable can not be found or invalid save_mem is set to zero in get_config_file() in main.c
```

What happens when you start with only -d or other option (e.g. -r)

Regards,

Paul

Van: GeorgN [mailto:notifications@github.com] 
Verzonden: donderdag 21 april 2016 12:35
Aan: paulvha/rfid-rc522 rfid-rc522@noreply.github.com
CC: paulvha paulvha@outlook.com; Comment comment@noreply.github.com
Onderwerp: Re: [paulvha/rfid-rc522] Issue while doing ./mc (#1)

thanks ... after the modification the compiler worked.

By testing the program rc522 I 've got following results:
1. ./rc522 [options]: (version 1.11)
-d enable debug mode
-w write to card block
-r read a card block
-s save content all card blocks in a file
-p perform action on card number (specified in configuration file)
-c change access rights for specific block
-a perform action based on content specific block
-k Change authentication key on a specific sector
That seems to be ok.
2. ./rc522 -s
and nothing happened ...

**Comment by GeorgN** [comment]
Hi Paul, I've double checked it, all is ok. 
Running -d option, I#ve got "Debug mode."
So I've checked the wiring and there I did see, that reset should be on pin 15 (BCM 22). But in main.c row 113 there is
    bcm2835_spi_begin();    // set pins 19, 21, 23, 24, 26
Is there the issue?
Regards
Georg

**Comment by paulvha** [comment]
spi is set by BCM2835_spi_begin.
pin 19  MOSI (Master out, slave in)
pin 21 MISO ( Master in, Slave out)
pin 23 clock
pin 24 select 0
pin 26 select 1
The reset is pin is  on line 101 (and it read from the config file from GPIO=22 is default) which is pin 15
If you only use -d as option, if should tell "will still handle 10 cards" and "hold your card for the reader". That is if the value of loop is > 0, which is set in the config file.  Try to put printf() on the lines
e.g. printf("this is line 1457\n"); this will help to understand where the program fails.

**Comment by GeorgN** [comment]
Thanks Paul :-)
So wiring is ok, I don't use pin 26 because I've only one RC522 module working and so don't need select 1. For reset I'm using the default option.

Next step was analyzing the program behaviour according to your suggestion:
    /\* read /etc/rc522.conf */
    if (get_config_file()) exit(1);
       printf("is reading config\n");

```
/* set BCM2835 Pins correct */
if (HW_init(spi_speed,gpio)) close_out(1);
   printf("setting bcm pins\n");

/* read & set GID and UID from config file */
if (read_conf_uid()!= 0) close_out(1);
   printf("read and set gid and uid from config\n");


while (loop > 0){
      printf("starting loop\n");
    if ((loop != prev_loop) && (endless == 0)){
        printf("\nWill still handle %d cards\n", loop);
        prev_loop = loop;
```

Here is the output:
sudo ./rc522 -s
is reading config
setting bcm pins
read and set gid and uid from config

I'm missing "starting loop", is there a bug? Sorry for my newbie questions, but I have no idea ...

Best regards Georg

**Comment by paulvha** [comment]
that is good progress George. It would indicate the value loop is NOT larger than 0.
I checked the code, there is an error between instruction in RC522.conf and code . It states that a value of 0 would drive an endless loop, however in the code (line 550) I check for a negative value to endless loop.
will post an updated version (1.12) in minutes.

**Comment by GeorgN** [comment]
Hi Paul, 
Thank you very much for your great support! I've tried out your code, it works! You did a great job!
Best regards Georg

**Comment by paulvha** [comment]
That is good news. sorry for the hick-ups...
