### ISSUE TITLE
Not able to read ouptut from another process

### ISSUE THREAD

**Issue by ghost** [paulvha/rfid-rc522#2]
I am tyring to implement this with another process, where i can read the stdout of the main.c and get card details.

Ex: ./rc522.c | ./sample.c

my sample.c contains simple read  operation from stdout, when i check with any other program which prints output like "hello world" continously in infinite loop, i am able to read it from sample.c. When i test with rc522, i am not able to read anything.

**Comment by paulvha** [comment]
The code is using stdout for output and as such this should work.  You will have to provide an option (e.g. ./rc522 -h will display help) otherwise you will see no output from the program. Let me know if it  does solve your issue. (can also try ./rc522 -h | more)

**Comment by ghost** [comment]
i have checked it with ./rc522 -p its working, thanks for the support.
