### ISSUE TITLE
I can only read uid of tag's like card, not the rectangular

### ISSUE THREAD

**Issue by pourjour** [paulvha/rfid-rc522#4]
I'm trying to use your library  with MFRC522 reader to read different cards (MIFARE Classic 1K) but I'm getting a weird behaviour. the card cannot identify the presence of rectangular shaped card, but can detect the ones like a key holder (blue circular one). I checked the wirings and SPI speed clock, and everything seems OK.Do you have any Idea how to fix that or am I the only one facing this?

**Comment by paulvha** [comment]
Never had an issue like that.  Someone else contacted some time ago we had random read errors. (some cards worked others did not). We diagnosed that to a timing issue and as a result the -e option for the command line was included (enabling an extra wait/delay). Have you tried the -e-option on the command line ?  regards, Paul.

**Comment by pourjour** [comment]
Thanks for the fast response,
I tried the -e option (I think it doesn't take a parameter), but when I've
added "PcdReset()" just before find_tag() in get_card_info() , I could have
read the cards, but now I have errors when reading blocks (I can read some
of them but the others not, it's arbitrary)

Thanks again

**Comment by paulvha** [comment]
-e does not a parameter. what you could try is in RC522.c, PcdComMF522(), line 737 : if (extra_delay) usleep(500);. experiment with increasing the value of 500 . This is the extra delay that is triggered with -e and was needed for some cards.

**Comment by pourjour** [comment]
Thank you I will try to test it, I think I have electricity power problem. When I change the adapter it works a little bit fine

**Comment by paulvha** [comment]
closing old issues
